/*
 * This source file was generated by the Gradle 'init' task
 */
package com.fcm.Practica01;

import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.TextField;
import javafx.application.Application;
import static javafx.application.Application.launch;
import javafx.geometry.Insets;
import javafx.scene.Scene;
import javafx.scene.control.Alert;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;

/**
 * Plantilla JAVAFX
 * Autor: Francisco Crespo martín
 * Curso y año: 2 DAM B
 * Objetivo de esta clase: Aplicar descuentos
 */
public class Ejercicio01 extends Application {

    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) {
        
        Label lblPrecio = new Label("Precio (€)");
        TextField txtPrecio = new TextField();
        
        Label lblDescuento = new Label("Descuento (%)");
        TextField txtDescuento = new TextField();
        
        Button btnCalcular = new Button("Calcular");

        VBox vbox=new VBox(10);
        vbox.getChildren().add(lblPrecio);
        vbox.getChildren().add(txtPrecio);
        vbox.getChildren().add(lblDescuento);
        vbox.getChildren().add(txtDescuento);
        vbox.getChildren().add(btnCalcular);
        
        btnCalcular.setOnAction((event) -> {
            double precio = Integer.parseInt(txtPrecio.getText());
            double descuento = Integer.parseInt(txtDescuento.getText());
            double descontado = (precio*descuento)/100;
            Alert alerta = new Alert(Alert.AlertType.INFORMATION);
            alerta.setTitle("Info");
            alerta.setHeaderText("Descuento aplicado. Precio inicial " + precio);
            alerta.setContentText("Descuento: " + descontado + " Precio final: " + (precio - descontado));
            alerta.showAndWait();
        });
        
        vbox.setPadding(new Insets(20));
        Scene scene=new Scene(vbox, 300,200);
        primaryStage.setScene(scene);
        primaryStage.setTitle("Calculadora de Descuentos");
        primaryStage.show();
    }

}

