/*
 * This source file was generated by the Gradle 'init' task
 */
package com.fcm.Practica01;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
       Ejercicio01p classUnderTest = newEjercicio01p();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
