/*
 * This source file was generated by the Gradle 'init' task
 */
package com.fcm.LanzadorComponentes;

import java.io.IOException;
import javafx.application.Application;
import static javafx.application.Application.launch;
import javafx.fxml.FXMLLoader;
import javafx.geometry.Insets;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;

public class App extends Application {

    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) {

        /*VBox vbox=new VBox(10); //Layout padre (contenedor de nodos). 10 px separación
        vbox.setPadding(new Insets(20));//Borde interno 20px
        Scene scene=new Scene(vbox, 500,400);
        primaryStage.setScene(scene);*/
        
        
        FXMLLoader loader = new FXMLLoader(getClass().getResource("prueba.fxml"));
        System.out.println(getClass().getResource("prueba.fxml"));
        try {
            
            Parent root = loader.load();
            Scene escena = new Scene(root);
            primaryStage.setScene(escena);
            /*destino.setTitle("Lanzador");
            destino.setResizable(false);
            destino.centerOnScreen();*/
        } catch (IOException ex) {
            System.err.println(ex.getMessage());
        }
        primaryStage.show();
    }

}
