# docker-compose -f postgresql_pgadmin.yml -p postgresql_pgadmin up
# Al registrar el servidor con pgAdmin utilizar como nombre/dirección del servidor: postgresql_server
version: "3.8"

services:
  postgresql:
    image: postgres
    container_name: postgresql_server
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
#    volumes:
#      - ./postgresql_data:/var/lib/postgresql/data
    networks:
      - postgresql

  pgadmin:
    image: dpage/pgadmin4
    container_name: postgresql_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@gmail.com
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 80:80
#    volumes:
#      - ./pgadmin:/var/lib/pgadmin
    networks:
      - postgresql
    depends_on:
      - postgresql

networks:
  postgresql:
    driver: bridge
